### ISSUE TITLE
NullPointerException in PlotManager.java:246

### ISSUE THREAD

**Issue by Nachwahl** [AlpsBTE/PlotSystem#10]
```java.lang.NullPointerException: null
	at github.BTEPlotSystem.core.system.plot.PlotManager.lambda$checkPlotsForLastActivity$1(PlotManager.java:246) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]```

**Comment by LordTuxn** [comment]
Fixed the NullPointerException in this commit https://github.com/AlpsBTE/PlotSystem/commit/e0eb01ffb827e92fdc417da4203681aa2eea13eb

The error should normally not occur but just to be safe 👍
