### ISSUE TITLE
[Bug] - Error during plot generation when player has all slots occupied

### ISSUE THREAD

**Issue by LordTuxn** [AlpsBTE/PlotSystem#14]
```[
23:29:47 INFO]: [WorldGuard] (P-6) TNT ignition is PERMITTED.
[23:29:47 INFO]: [WorldGuard] (P-6) Lighters are PERMITTED.
[23:29:47 INFO]: [WorldGuard] (P-6) Lava fire is blocked.
[23:29:47 INFO]: [WorldGuard] (P-6) All fire spread is disabled.
[23:29:47 INFO]: [WorldGuard] Loaded configuration for world 'P-6'
[23:29:47 INFO]: [Multiverse-Core] Loading World & Settings - 'P-6' - Env: NORMAL - Type: FLAT & generator: VoidGenerator
[23:29:47 WARN]: [Multiverse-Core] Spawn location from world.dat file was unsafe. Adjusting...
[23:29:47 WARN]: [Multiverse-Core] Original Location: X: -102 Y: 4 Z: 1,048 P: 0 Y: 0 
[23:29:47 ERROR]: [Multiverse-Core] Safe spawn NOT found!!!
[23:29:47 WARN]: [Multiverse-Core] Somebody tried to set the spawn location for 'P-6' to an unsafe value! Adjusting...
[23:29:47 WARN]: [Multiverse-Core] Old Location: X: -102 Y: 4 Z: 1,048 P: 0 Y: 0 
[23:29:47 WARN]: [Multiverse-Core] New (unsafe) Location: X: 75.5 Y: 30 Z: 75.5 P: 90 Y: -90 
[23:29:47 WARN]: [Multiverse-Core] Couldn't fix the location. I have to abort the spawn location-change :/
[23:29:47 WARN]: [AlpsBTE-PlotSystem] Plugin AlpsBTE-PlotSystem v1.1.1 generated an exception while executing task 5212
java.lang.NullPointerException: null
        at github.BTEPlotSystem.core.system.Builder.setPlot(Builder.java:143) ~[?:?]
        at github.BTEPlotSystem.core.system.plot.PlotGenerator.lambda$new$1(PlotGenerator.java:91) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [server.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
```

**Comment by LordTuxn** [comment]
Fixed in https://github.com/AlpsBTE/PlotSystem/commit/f3e27bd9fa9605f2333d9c17c359c59473843c4a
